# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install GTest
        run: |
          echo Install GTest,
          wget https://github.com/google/googletest/archive/release-1.12.1.tar.gz
          tar xf release-1.12.1.tar.gz
          cd googletest-release-1.12.1
          cmake -DBUILD_SHARED_LIBS=ON .
          make
          ls -lah
          sudo cp -a googletest/include/gtest /usr/include
          sudo cp -a lib/libgtest_main.so lib/libgtest.so /usr/lib/
          sudo make install
          sudo ldconfig -v | grep gtest

      - name: Run script for 'Compilacion paso a paso'
        working-directory: ./compilacion_pasos
        run: sh compile.sh
      
      - name: Run script for 'Compilacion modulo'
        working-directory: ./compilacion_modulo
        run: sh compile.sh

      - name: Run script for 'Compilacion modulo Makefile'
        working-directory: ./compilacion_modulo_makefile
        run: sh compile.sh

      - name: Run script for 'Compilacion modulo CMake'
        working-directory: ./compilacion_modulo_cmake
        run: sh compile.sh

      - name: Run script for 'Libreria estatica'
        working-directory: ./lib_estatica
        run: sh compile.sh
      
      - name: Run script for 'Libreria dinamica'
        working-directory: ./lib_dinamica
        run: sh compile.sh

      - name: Run script for 'Compilacion modulos CMake con tests'
        working-directory: ./modulos_cmake_testing
        run: sh compile.sh
